### ISSUE TITLE
buildroot tries to download msd45 binary package from boris instead of github

### ISSUE THREAD

**Issue by dsiganos** [LairdCP/wb-buildroot#1]
On release 3.5.1.43, the file
<pre>
buildroot/package/lrd/msd45n-binaries/msd45n-binaries.mk
</pre>
points to boris as the location to download the msd45 package from.

It should  be pointing to github instead.

**Comment by derosier** [comment]
Unfortunately, we don't officially publish our msd binaries on github, and we have to use the download location internally as part of our build processes. buildroot doesn't provide a method to have multiple sites, which is really what's necessary to fix this issue.

**The recommended solution is to take the msd package as published on lairdtech.com and place it in your BUILDROOT_DL_DIR before building**, as outlined here: https://github.com/LairdCP/wb-manifests/blob/master/README.md#cant-find-the-msd-package 

This is a long-standing enhancement request in our system that we've yet to have a solution to. For now we're unable to address this issue beyond providing the instructions on how to deal with the situation.
